import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Portal Metal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <div className="container">
      <header className={styles.header}>
        <a href="#home">
          <img
            className={styles.log}
            src={`/$/logoyoutube.png`}
            alt="logo"></img>
        </a>
        <nav>
          <ul className={styles.menu}>
            <li>
              <a href="#home">HOME</a>
            </li>
            <li>
              <a href="#profile">ANUNCIE AQUI</a>
            </li>
            <li>
              <a href="#content">CONTATO</a>
            </li>
          </ul>
        </nav>
      </header>
      </div>
      <div className={styles.banner}>
        <Image
        src="/urso/capasite.jpg"
        width="1000px"
        height="300px"
        layout="fixed"
        />

 </div>       
      
      <main className={styles.main}>
             <section className={styles.content}>
          <div className={styles.contat}>
          <h2>PROCURE SUA BANDA PREFERIDA </h2>
          <form className={styles.form} method="POST" action="./email.php">
          <input
              className={styles.field}
              name="Nome"
              placeholder="Nome da Banda"></input>
           <input
              className={styles.field}
              name="estilo"
              placeholder="Estilo"></input>
            <input type="submit" value="Procurar"></input>
          </form>
        </div>
      
        

        {/* <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p> */}
         
  
          <div className={styles.contat}>
          <h2>ANUNCIE SUA BANDA CONOSCO </h2>
            <form className={styles.form} method="POST" action="./email.php">
            <input
              className={styles.field}
              name="Nome"
              placeholder="Nome da Banda"></input>
            <input
              className={styles.field}
              name="email"
              placeholder="E-mail"></input>
             <input type="submit" value="Enviar"></input><br></br>
            
          </form>
    
</div>
</section>

<h1 className={styles.parceiros}>BANDAS PARCEIRAS</h1>

        <div className={styles.grid}>
          <Link href="/band/urso">
            <a className={styles.card}>
            <img src="../ursoperfil.jpg" alt="foto urso"></img>
            </a>
          </Link>
          <Link href="/band/almanegra">
            <a className={styles.card}>
              <h2>Alma Negra</h2>
              <p>Alma Negra</p>
            </a>
          </Link>
          <Link href="/band/slammer">
            <a className={styles.card}>
              <h2>Slammer</h2>
              <p>
                Slammer
              </p>
            </a>
          </Link>
          
<br></br>
          {/* <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}>
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}>
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a> */}
        </div>
        <section className={styles.content}>
        <div className={styles.cadastro}>
          <h2>CADASTRE SUA BANDA </h2>
          <form className={styles.form} method="POST" action="./email.php">
            <input
              className={styles.field}
              name="Nome"
              placeholder="Nome da Banda"></input>
            <input
              className={styles.field}
              name="email"
              placeholder="E-mail"></input>
            <textarea
              className={styles.field}
              name="mesage"
              placeholder="Realese e Redes Sociais"></textarea>
              <h3>ADD FOTOS</h3>
               <input type="file" id="flimage" name="flimage" accept="image*/"></input><br></br>
            <input type="submit" value="Enviar"></input><br></br>
            
          </form>
        </div>
      </section>
      </main>

       <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer">
          PORTAL METAL DIREITOS RESERVADOS{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> 
    </div>
  );
}
